-- Selecionando o DB a ser usado
USE `needhelpappfiap`;

-- Criação da tabela de categorias
CREATE TABLE `NHAF_CATEGORIAS` (
  `CTG_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CTG_NOME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CTG_ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- Criação da tabela de páginas
CREATE TABLE `NHAF_PAGINAS` (
  `PG_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PG_CTG_ID` BIGINT(20) UNSIGNED NOT NULL,
  `PG_NOME` VARCHAR(50) NOT NULL,
  `PG_IDAUTOR` BIGINT(20) UNSIGNED NOT NULL,
  `PG_NOMEAUTOR` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`PG_ID`),
  FOREIGN KEY (`PG_CTG_ID`) REFERENCES NHAF_CATEGORIAS(`CTG_ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- Criação da tabela de procedimentos
CREATE TABLE `NHAF_PROCEDIMENTOS` (
  `PRC_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `PRC_PG_ID` BIGINT(20) UNSIGNED NOT NULL,
  `PRC_ORDEM` INT NOT NULL,
  `PRC_TITULO` VARCHAR(50) NOT NULL,
  `PRC_TAREFAS` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`PRC_ID`),
  FOREIGN KEY (`PRC_PG_ID`) REFERENCES NHAF_PAGINAS(`PG_ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- Criação da tabela de recursos
CREATE TABLE `NHAF_RECURSOS` (
  `REC_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `REC_PG_ID` BIGINT(20) UNSIGNED NOT NULL,
  `REC_ORDEM` INT NOT NULL,
  `REC_LINKVIDEO` VARCHAR(200) NULL,
  `REC_LINKLEITURA` VARCHAR(200) NULL,
  `REC_LINKIMAGEM` VARCHAR(200) NULL,
  PRIMARY KEY (`REC_ID`),
  FOREIGN KEY (`REC_PG_ID`) REFERENCES NHAF_PAGINAS(`PG_ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
