-- Selecionando o DB a ser usado
USE `needhelpappfiap`;

-- Criação da tabela de usuários
CREATE TABLE `NHAF_USUARIOS` (
  `USR_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `USR_LOGIN` VARCHAR(50) NOT NULL,
  `USR_SENHA` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`USR_ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- Criação da tabela de favoritos
CREATE TABLE `NHAF_FAVORITOS` (
  `FAV_ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `FAV_USR_ID` BIGINT(20) UNSIGNED NOT NULL,
  `FAV_PG_ID` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`FAV_ID`),
  FOREIGN KEY (`FAV_USR_ID`) REFERENCES NHAF_USUARIOS(`USR_ID`),
  FOREIGN KEY (`FAV_PG_ID`) REFERENCES NHAF_PAGINAS(`PG_ID`)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
